import type { Lesson } from "./types";

export interface AcademyStep { title: string; explanation: string; checkpoint: string }
export interface AcademyLesson {
  id: string; order: number; track: "comece-aqui"|"interpretacao"|"conducao"|"arritmias"|"repolarizacao"|"metodos"|"marcapasso"|"emergencias";
  title: string; subtitle: string; duration: string; sourceCourseId: string;
  status: "reviewed"|"mapped"|"pending"; visual: Lesson["visual"];
  objectives: string[]; steps: AcademyStep[];
}
export const academyTrackNames = {"comece-aqui":"Comece aqui",interpretacao:"Interpretação básica",conducao:"Condução e bloqueios",arritmias:"Arritmias",marcapasso:"Marcapasso",repolarizacao:"Repolarização e canalopatias",metodos:"Métodos complementares",emergencias:"Aplicação e emergências"};

export const academyLessons: AcademyLesson[] = [
 {id:"zero-01",order:1,track:"comece-aqui",title:"Do coração ao vetorcardiograma",subtitle:"Eletricidade, condução, ciclo cardíaco e vetores antes de interpretar",duration:"45 min",sourceCourseId:"334+314",status:"reviewed",visual:"normal",objectives:["Distinguir atividade elétrica de contração","Relacionar sístole e diástole aos eventos elétricos","Percorrer o sistema de condução na ordem correta","Entender polarização, despolarização e repolarização","Construir e projetar vetores elétricos","Entender como nasce o vetorcardiograma","Explicar por que uma onda sobe, desce ou fica bifásica"],steps:[
  {title:"Eletricidade antes do movimento",explanation:"O traçado registra diferenças de potencial produzidas pela ativação e recuperação das células cardíacas. Ele não desenha diretamente a contração. A atividade mecânica ocorre depois do evento elétrico e precisa de outros dados para ser avaliada.",checkpoint:"Se o QRS existe, isso não prova que o ventrículo contraiu adequadamente; prova que houve atividade elétrica registrada."},
  {title:"Um vetor tem direção",explanation:"Em cada instante, muitas células participam do fenômeno. A soma dessas forças pode ser representada por um vetor. A mesma ativação gera traçados diferentes conforme o ponto de observação.",checkpoint:"Antes de decorar uma forma, pergunte se a força se aproxima ou se afasta do polo positivo."},
  {title:"Positivo, negativo ou isoelétrico",explanation:"Uma força dirigida ao polo positivo tende a gerar deflexão positiva; afastando-se, negativa. Forças que se cancelam ou ficam perpendiculares podem produzir registro pequeno ou bifásico.",checkpoint:"Linha próxima do basal não significa coração eletricamente parado."},
  {title:"A célula começa polarizada",explanation:"Em repouso, a membrana mantém concentrações iônicas diferentes dentro e fora da célula. Essa separação de cargas cria um potencial elétrico e permite que a célula responda a um estímulo.",checkpoint:"Polarizada significa que existe diferença elétrica através da membrana; não significa que a célula esteja se contraindo."},
  {title:"Despolarizar e repolarizar",explanation:"Durante a ativação, correntes iônicas modificam rapidamente o potencial da membrana: é a despolarização. Depois, outras correntes restauram progressivamente o estado elétrico de repouso: é a repolarização.",checkpoint:"Despolarização e repolarização são eventos elétricos. Contração e relaxamento são consequências mecânicas relacionadas, mas não são desenhadas diretamente pelo ECG."},
  {title:"Da célula ao traçado de superfície",explanation:"As células cardíacas se conectam eletricamente e a ativação se propaga pelo tecido. O ECG de superfície representa a soma espacial e temporal dessas correntes, e não o potencial de ação isolado de uma única célula.",checkpoint:"A forma de uma onda depende de quais regiões estão ativas, da direção da propagação e da derivação que observa o fenômeno."},
  {title:"Tecidos não respondem todos da mesma forma",explanation:"Músculo atrial, ventricular e sistema His–Purkinje apresentam resposta rápida; nó sinusal e nó AV apresentam resposta lenta e automatismo próprio. Essa diferença ajuda a entender formação do ritmo e atraso fisiológico da condução AV.",checkpoint:"“Rápida” e “lenta” descrevem propriedades elétricas celulares, não apenas a frequência cardíaca."},
  {title:"O caminho normal da condução",explanation:"O impulso normalmente começa no nó sinusal, espalha-se pelos átrios, alcança o nó AV, percorre o feixe de His, os ramos direito e esquerdo e a rede de Purkinje. A organização desse caminho permite ativar primeiro os átrios e depois os ventrículos de modo rápido e coordenado.",checkpoint:"Recite a sequência sem olhar: nó sinusal → átrios → nó AV → His → ramos → Purkinje → miocárdio ventricular."},
  {title:"Por que o nó AV atrasa",explanation:"A condução pelo nó AV é fisiologicamente lenta. Esse intervalo elétrico ajuda a separar a ativação atrial da ventricular e permite que o enchimento ventricular aconteça antes da contração dos ventrículos.",checkpoint:"O atraso AV normal é organização do ciclo; não deve ser confundido automaticamente com bloqueio."},
  {title:"Sístole e diástole não são ondas",explanation:"Sístole e diástole descrevem fases mecânicas. A sístole ventricular é precedida pela despolarização ventricular representada pelo QRS; a recuperação elétrica ventricular aparece principalmente na onda T e antecede o relaxamento mecânico. Os limites mecânicos não coincidem perfeitamente com uma única onda do ECG.",checkpoint:"QRS não é sinônimo de sístole e T não é sinônimo de diástole: o ECG registra os eventos elétricos relacionados."},
  {title:"Um ciclo liga eletricidade e mecânica",explanation:"A onda P precede a contração atrial. O QRS precede a elevação de pressão e a ejeção ventricular. A onda T acompanha a recuperação elétrica que permite o relaxamento subsequente. Válvulas, pressões e fluxo pertencem ao ciclo mecânico e não são medidos diretamente pelo ECG.",checkpoint:"Ao relacionar ECG e ciclo cardíaco, use a palavra “precede” ou “se relaciona”, evitando dizer que a onda é a própria contração."},
  {title:"O vetor muda a cada instante",explanation:"A ativação não produz uma única seta imóvel. Conforme novas regiões despolarizam e outras já estão totalmente ativadas, o vetor resultante muda de direção e magnitude. Cada ponto do QRS representa um momento diferente dessa sequência.",checkpoint:"Uma morfologia complexa nasce de vários vetores instantâneos sucessivos, não de uma única força constante."},
  {title:"Da seta à alça vetorial",explanation:"Se registrarmos a extremidade dos vetores instantâneos em sequência, formamos uma alça no espaço. O vetorcardiograma representa essa trajetória das forças elétricas, enquanto cada derivação do ECG mostra uma projeção dessa trajetória sobre um eixo de observação.",checkpoint:"Vetorcardiograma é a trajetória espacial; derivação eletrocardiográfica é uma projeção dessa trajetória."},
  {title:"Planos frontal e horizontal",explanation:"As derivações dos membros projetam as forças principalmente no plano frontal. As precordiais observam o plano horizontal. Integrar os dois planos ajuda a compreender eixo, progressão de R e alterações que não aparecem igualmente em todas as derivações.",checkpoint:"Antes de interpretar uma deflexão, diga qual plano e qual eixo de observação estão sendo usados."},
  {title:"A mesma alça produz doze perspectivas",explanation:"O coração realiza uma sequência elétrica comum, mas as doze derivações a observam de ângulos diferentes. Uma força pode aproximar-se do polo positivo de uma derivação e afastar-se de outra, produzindo deflexões opostas sem que exista contradição.",checkpoint:"Doze derivações não são doze batimentos diferentes; são doze perspectivas elétricas organizadas."}]},
 {id:"zero-02",order:2,track:"comece-aqui",title:"Papel, calibração e tempo",subtitle:"A régua que impede interpretações falsas",duration:"10 min",sourceCourseId:"314",status:"reviewed",visual:"normal",objectives:["Conferir velocidade e ganho","Converter quadrados em tempo","Reconhecer medidas não confiáveis"],steps:[
  {title:"Leia a régua antes do traçado",explanation:"Na calibração usual, o papel corre a 25 mm/s e 10 mm representam 1 mV. Esses valores precisam ser conferidos: mudar velocidade ou ganho muda a aparência sem mudar o coração.",checkpoint:"Nunca calcule frequência ou duração antes de verificar a calibração."},
  {title:"Quadrados viram milissegundos",explanation:"A 25 mm/s, cada quadrado pequeno horizontal corresponde a 40 ms; um quadrado grande, formado por cinco pequenos, corresponde a 200 ms.",checkpoint:"Cinco quadrados grandes representam um segundo."},
  {title:"Qualidade faz parte da leitura",explanation:"Artefato, derivações trocadas, linha de base instável e corte do sinal podem simular alterações. Quando o registro é inadequado, reconheça a limitação em vez de forçar um diagnóstico.",checkpoint:"Uma medida só é válida se o início e o fim do evento estiverem visíveis."}]},
 {id:"int-01",order:3,track:"interpretacao",title:"A frase P–QRS–T",subtitle:"Reconheça ondas, segmentos e intervalos",duration:"15 min",sourceCourseId:"314",status:"reviewed",visual:"normal",objectives:["Localizar P, QRS e T","Distinguir segmento de intervalo","Relacionar elementos à sequência elétrica"],steps:[
  {title:"P inicia a frase",explanation:"A onda P representa a despolarização atrial. Mais importante que apenas vê-la é observar sua relação temporal com os complexos QRS.",checkpoint:"Procure P em várias derivações e veja se mantém relação organizada com QRS."},
  {title:"PR mede uma viagem",explanation:"O intervalo PR começa no início da onda P e termina no início do QRS. Inclui a ativação atrial e a condução até o começo da ativação ventricular.",checkpoint:"O PR é intervalo e inclui uma onda; o segmento PR é apenas parte dele."},
  {title:"QRS ativa, ST conecta, T recupera",explanation:"O QRS representa a despolarização ventricular. O segmento ST liga o final do QRS à onda T, relacionada principalmente à repolarização ventricular.",checkpoint:"A onda T representa fenômeno elétrico, não o relaxamento mecânico diretamente."}]},
 {id:"int-02",order:4,track:"interpretacao",title:"Derivações são câmeras elétricas",subtitle:"Planos frontal e horizontal sem decorar às cegas",duration:"18 min",sourceCourseId:"314",status:"mapped",visual:"normal",objectives:["Separar periféricas e precordiais","Entender derivações contíguas","Relacionar território e vetor"],steps:[
  {title:"Doze registros, dez eletrodos",explanation:"Derivações dos membros observam o plano frontal; precordiais, o plano horizontal. Cada derivação é uma diferença de potencial, não um eletrodo isolado.",checkpoint:"Diga qual plano está sendo observado antes de interpretar direção."},
  {title:"Contiguidade é vizinhança",explanation:"Derivações contíguas observam regiões relacionadas. Uma alteração coerente em vizinhas tem significado diferente de um achado solitário.",checkpoint:"Não localize uma alteração por uma única derivação sem conferir as vizinhas."},
  {title:"V1 e V6 contam lados diferentes",explanation:"V1 destaca forças anteriores e direitas; derivações laterais observam forças dirigidas à parede lateral esquerda. Compará-las é central na análise de condução.",checkpoint:"Nos bloqueios, pergunte onde o QRS termina positivo e onde termina negativo."}]},
 {id:"int-03",order:5,track:"interpretacao",title:"Leitura sistemática completa",subtitle:"Uma ordem fixa para reduzir omissões",duration:"20 min",sourceCourseId:"314",status:"reviewed",visual:"normal",objectives:["Aplicar sequência reproduzível","Separar achados de conclusão","Evitar diagnóstico por impressão"],steps:[
  {title:"Comece pela validade",explanation:"Confira qualidade, calibração e velocidade. Depois estime frequência e regularidade.",checkpoint:"Se a régua estiver errada, os cálculos seguintes também podem estar."},
  {title:"Acompanhe a condução",explanation:"Analise P, relação P–QRS, PR, duração e morfologia do QRS. Só então determine eixo e progressão precordial.",checkpoint:"Descrever QRS como estreito ou largo vem antes de nomear um bloqueio."},
  {title:"Feche com repolarização e síntese",explanation:"Avalie ST, T e QT no contexto do QRS e das derivações. A conclusão deve reunir apenas achados demonstrados.",checkpoint:"Uma conclusão forte pode ser reconstruída a partir dos critérios descritos."}]},
 {id:"int-04",order:6,track:"interpretacao",title:"Idade muda o normal",subtitle:"Particularidades do ECG infantil",duration:"16 min",sourceCourseId:"321",status:"mapped",visual:"fast",objectives:["Reconhecer variação com idade","Evitar critérios adultos automáticos","Usar contexto e tabelas validadas"],steps:[
  {title:"Normal não é universal",explanation:"Frequência, intervalos, eixo e predominância ventricular mudam durante o desenvolvimento. Um padrão esperado em uma idade pode ser inadequado em outra.",checkpoint:"Confirme a faixa etária da referência antes de comparar limites."},
  {title:"O coração direito começa evidente",explanation:"A circulação fetal e a transição pós-natal influenciam as forças ventriculares. A progressão para o padrão adulto ocorre com o crescimento.",checkpoint:"Não classifique força direita como patológica sem considerar idade."},
  {title:"A leitura continua sistemática",explanation:"A sequência permanece: técnica e artefatos, frequência, ritmo, P, PR, QRS, eixo, QT/QTc, ST e T. O que muda são os valores esperados e a morfologia normal em cada fase do desenvolvimento.",checkpoint:"Use tabela pediátrica validada para a idade; não aplique automaticamente limites adultos."},
  {title:"Onda T também amadurece",explanation:"A direção da onda T nas precordiais direitas se modifica no período neonatal e na infância. Uma inversão que seria suspeita em adulto pode fazer parte da evolução pediátrica normal.",checkpoint:"Data de nascimento e idade gestacional fazem parte da interpretação."},
  {title:"Tabelas precisam ser aprovadas",explanation:"O beta ensina o princípio; limites pediátricos só serão liberados após validação detalhada das tabelas e das discussões de casos.",checkpoint:"CONTEÚDO NUMÉRICO PEDIÁTRICO AINDA NÃO LIBERADO PARA EXERCÍCIOS."}]},
 {id:"cond-01",order:7,track:"conducao",title:"Sobrecarga: pense em forças",subtitle:"Átrios, ventrículos e repolarização associada",duration:"18 min",sourceCourseId:"324",status:"mapped",visual:"lvh",objectives:["Separar sinais atriais e ventriculares","Entender limites dos critérios","Integrar voltagem, eixo e morfologia"],steps:[
  {title:"Mais músculo pode mudar o vetor",explanation:"Alterações anatômicas ou de carga modificam duração, amplitude e direção das forças. Nenhum sinal isolado substitui integração com contexto e outros métodos.",checkpoint:"Voltagem alta sozinha não equivale automaticamente a hipertrofia."},
  {title:"Átrios aparecem primeiro",explanation:"A análise atrial começa na onda P: duração, amplitude, forma e componentes em derivações apropriadas.",checkpoint:"Descreva qual parte da P mudou antes de nomear a câmara."},
  {title:"Átrio direito e átrio esquerdo mudam partes diferentes da P",explanation:"Forças direitas tendem a aumentar a porção inicial e a amplitude da P em derivações inferiores; forças esquerdas prolongam a ativação atrial e aumentam a porção terminal negativa em V1. A análise deve combinar duração, amplitude e morfologia.",checkpoint:"Evite reduzir sobrecarga atrial a “P alta” ou “P larga” sem dizer onde e qual componente mudou."},
  {title:"Ventrículos exigem conjunto",explanation:"Forças precordiais, derivações dos membros, eixo e repolarização formam conjuntos de critérios. Voltagem elevada isolada pode ocorrer sem sobrecarga anatômica.",checkpoint:"O ECG sugere padrão de sobrecarga; ecocardiograma e contexto respondem perguntas anatômicas diferentes."},
  {title:"Repolarização pode acompanhar a sobrecarga",explanation:"Alterações secundárias de ST e T podem surgir quando a sequência de ativação e recuperação ventricular é modificada. Elas precisam ser distinguidas de isquemia e outros diagnósticos diferenciais.",checkpoint:"Descreva a distribuição do padrão de repolarização e relacione-a ao QRS."},
  {title:"Associações tornam os critérios menos simples",explanation:"Bloqueios de ramo, bloqueios fasciculares e sobrecarga de mais de uma câmara podem mascarar ou modificar voltagens e eixos.",checkpoint:"CRITÉRIOS NUMÉRICOS PERMANECEM FORA DOS DESAFIOS ATÉ A REVISÃO DOS CASOS."}]},
 {id:"cond-02",order:8,track:"conducao",title:"Bloqueios de ramo",subtitle:"Duração, V1, lateral e forças terminais",duration:"20 min",sourceCourseId:"325+337",status:"reviewed",visual:"rbbb",objectives:["Reconhecer atraso intraventricular","Comparar V1 e lateral","Justificar BRD ou BRE por critérios"],steps:[
  {title:"Primeiro: o QRS está alargado?",explanation:"O atraso modifica o tempo total de ativação ventricular. A duração abre a análise, mas não identifica sozinha o ramo comprometido.",checkpoint:"QRS largo é uma categoria de achado, não o diagnóstico completo."},
  {title:"Segundo: leia o final do QRS",explanation:"As forças terminais mostram qual ventrículo foi ativado por último. Em padrão compatível com BRD, a ativação tardia direita/anterior tende a terminar positiva em V1 e a afastar-se das laterais.",checkpoint:"Compare V1 e lateral; não aceite rótulo sem coerência."},
  {title:"Terceiro: procure associações",explanation:"Bloqueios coexistem com alterações de eixo, sobrecarga ou outros distúrbios. Diferencie critérios primários de alterações secundárias.",checkpoint:"Não descarte outros achados depois de reconhecer o padrão de ramo."}]},
 {id:"cond-03",order:9,track:"conducao",title:"Fascículos e eixo",subtitle:"Quando o atraso muda o plano frontal",duration:"18 min",sourceCourseId:"338",status:"pending",visual:"lafb",objectives:["Relacionar fascículos ao eixo","Diferenciar eixo de bloqueio fascicular","Reconhecer combinações"],steps:[
  {title:"O ramo esquerdo se divide",explanation:"A ativação esquerda distribui-se por fascículos. Atrasos seletivos redirecionam forças no plano frontal e alteram a sequência ventricular.",checkpoint:"Desvio de eixo é achado; bloqueio fascicular exige critérios adicionais."},
  {title:"Fascículo anterossuperior",explanation:"O atraso anterossuperior redireciona as forças no plano frontal para a esquerda e para cima, sem necessariamente alargar o QRS. O padrão inclui desvio do eixo e morfologias coerentes nas derivações inferiores e laterais.",checkpoint:"Eixo para a esquerda isolado não fecha o diagnóstico; confira morfologia e causas alternativas."},
  {title:"Fascículo posteroinferior",explanation:"O atraso posteroinferior desloca as forças para a direita e para baixo. É menos comum e exige exclusão cuidadosa de outras causas de eixo direito.",checkpoint:"Sobrecarga ventricular direita, doença pulmonar e variação anatômica podem confundir."},
  {title:"Divisão anteromedial",explanation:"O atraso da divisão anteromedial modifica principalmente as forças no plano horizontal e pode produzir ondas R proeminentes em V1–V2. A aula enfatiza que esse é um diagnóstico de exclusão.",checkpoint:"R ampla em V1 não significa automaticamente bloqueio anteromedial."},
  {title:"Combine duração, eixo e morfologia",explanation:"Não use apenas o quadrante do eixo. Duração, morfologia e exclusão de outras causas precisam ser integradas.",checkpoint:"CASOS COMPLEMENTARES AINDA EM REVISÃO; não há desafios liberados."}]},
 {id:"cond-04",order:10,track:"conducao",title:"Bloqueios atrioventriculares",subtitle:"Leia a relação entre P e QRS no tempo",duration:"28 min",sourceCourseId:"342",status:"reviewed",visual:"slow",objectives:["Avaliar relação P–QRS","Distinguir atraso de falha","Reconhecer os padrões de primeiro, segundo e terceiro graus","Descrever antes de classificar"],steps:[
  {title:"Conte átrios e ventrículos",explanation:"Identifique P, QRS e a relação entre eles. Compare PR sucessivos e procure batimentos não conduzidos.",checkpoint:"Uma única medida de PR não descreve a dinâmica de um bloqueio AV."},
  {title:"Primeiro grau: atraso sem falha",explanation:"No bloqueio AV de primeiro grau, todas as ondas P são conduzidas e o PR permanece constante, porém prolongado acima de 200 ms. O termo descreve atraso da condução, não perda de complexos QRS.",checkpoint:"Antes de medir PR, confirme velocidade do papel e identifique corretamente o início de P e do QRS."},
  {title:"Segundo grau tipo I",explanation:"No padrão de Wenckebach, o intervalo PR aumenta progressivamente até que uma onda P não seja seguida por QRS. Depois da pausa, a sequência recomeça.",checkpoint:"Procure a dinâmica de vários ciclos; uma onda P isolada sem QRS não basta."},
  {title:"Segundo grau tipo II",explanation:"No Mobitz II, ocorre interrupção súbita da condução: uma onda P deixa de ser conduzida sem o prolongamento progressivo do PR observado no tipo I.",checkpoint:"Diferencie uma P bloqueada de extrassístole atrial prematura bloqueada."},
  {title:"Condução 2:1 e bloqueio avançado",explanation:"Na condução 2:1, alternam-se uma P conduzida e uma P bloqueada; o traçado isolado pode não permitir distinguir tipo I de tipo II. Proporções como 3:1 ou 4:1 representam bloqueio AV avançado.",checkpoint:"Quando só existe um PR observável por ciclo, não invente a evolução que não está registrada."},
  {title:"Terceiro grau: dissociação AV",explanation:"No bloqueio AV total, átrios e ventrículos mantêm ritmos independentes: não existe relação fixa entre P e QRS, e a frequência atrial costuma superar a ventricular.",checkpoint:"Dissociação exige observar P atravessando diferentes posições do ciclo ventricular, não apenas uma bradicardia."},
  {title:"Segurança educacional",explanation:"Bradicardia e bloqueios avançados podem representar emergência. O jogo ensina reconhecimento, nunca conduta para paciente real.",checkpoint:"Em pessoa sintomática ou instável, procure atendimento e siga protocolos clínicos; não use o jogo para decidir conduta."}]},
 {id:"arr-01",order:11,track:"arritmias",title:"Como uma arritmia começa e se mantém",subtitle:"Automatismo, atividade deflagrada e reentrada",duration:"24 min",sourceCourseId:"383+543",status:"reviewed",visual:"svt",objectives:["Separar formação e propagação anormais do impulso","Entender automatismo anormal","Distinguir pós-potenciais precoces e tardios","Explicar as condições necessárias para reentrada"],steps:[
  {title:"Comece pelo mecanismo",explanation:"Antes de decorar nomes, pergunte se o impulso nasceu de modo anormal, foi deflagrado por uma oscilação após o potencial de ação ou ficou circulando por um circuito de reentrada. Um mesmo aspecto eletrocardiográfico pode ter mecanismos diferentes.",checkpoint:"Mecanismo, diagnóstico e conduta são níveis distintos de raciocínio."},
  {title:"Automatismo anormal",explanation:"Células fora do marcapasso dominante podem adquirir despolarização espontânea mais rápida, especialmente em situações de isquemia, hipóxia, alterações iônicas ou estímulo adrenérgico. Em geral o foco acelera progressivamente e pode também desacelerar antes de desaparecer.",checkpoint:"Aceleração e desaceleração graduais favorecem automatismo; início abrupto favorece outros mecanismos."},
  {title:"Atividade deflagrada",explanation:"Oscilações do potencial de membrana podem aparecer durante a repolarização ou depois dela. Pós-potenciais precoces relacionam-se à repolarização prolongada e podem iniciar torsades de pointes; pós-potenciais tardios surgem após a repolarização e são favorecidos por sobrecarga intracelular de cálcio.",checkpoint:"O gatilho ocorre depois de um potencial de ação anterior; por isso não é automatismo espontâneo puro."},
  {title:"Reentrada precisa de um circuito",explanation:"Para um impulso recircular, costuma ser necessário um obstáculo anatômico ou funcional, bloqueio unidirecional, condução suficientemente lenta e recuperação do tecido à frente. O impulso retorna ao ponto inicial e encontra novamente tecido excitável.",checkpoint:"Um circuito rápido não se sustenta se alcançar tecido ainda refratário."},
  {title:"O ECG mostra pistas, não o circuito inteiro",explanation:"Início e término abruptos, regularidade, relação entre atividade atrial e ventricular e resposta a mudanças de condução ajudam a inferir o mecanismo. O traçado de superfície raramente demonstra sozinho toda a anatomia do circuito.",checkpoint:"Descreva o que o ECG prova antes de atribuir um mecanismo."}]},
 {id:"arr-02",order:12,track:"arritmias",title:"Flutter e taquicardias atriais",subtitle:"Leia a atividade atrial antes da resposta ventricular",duration:"28 min",sourceCourseId:"387+544",status:"reviewed",visual:"flutter",objectives:["Reconhecer ondas F do flutter","Diferenciar flutter, taquicardia atrial focal e multifocal","Analisar bloqueio e relação atrioventricular"],steps:[
  {title:"Não confunda frequência atrial com ventricular",explanation:"No flutter, a atividade atrial é rápida e organizada, mas o nó AV frequentemente conduz apenas parte dos impulsos. Por isso a frequência ventricular depende da relação de condução e pode ser regular ou variar.",checkpoint:"Conte as ondas atriais e os QRS separadamente."},
  {title:"Flutter típico: procure ondas F",explanation:"O flutter típico é uma macroreentrada no átrio direito. Ondas F contínuas, frequentemente em aspecto de serra e mais evidentes nas derivações inferiores, substituem as ondas P isoladas. A direção do circuito modifica a polaridade das ondas.",checkpoint:"Uma linha de base ondulada isolada não basta; confira organização, repetição e distribuição entre derivações."},
  {title:"Taquicardia atrial focal",explanation:"Um foco atrial fora do nó sinusal produz ondas P com morfologia diferente da sinusal antes dos QRS. A relação P:QRS pode variar se parte dos impulsos não atravessar o nó AV.",checkpoint:"Localize a P ectópica em várias derivações e não conclua pela frequência ventricular isolada."},
  {title:"Taquicardia atrial multifocal",explanation:"A atividade atrial é rápida e irregular, com pelo menos três morfologias distintas de P e intervalos PR variáveis. O padrão costuma aparecer em contexto clínico importante e pode ser confundido com fibrilação atrial.",checkpoint:"Na fibrilação atrial não há ondas P discretas repetíveis; na multifocal há P reconhecíveis, porém diferentes."},
  {title:"Tratamento não faz parte do jogo",explanation:"A aula original discute anticoagulação, cardioversão, fármacos e ablação. O beta usa apenas a lógica de reconhecimento do traçado; decisões terapêuticas exigem avaliação clínica e diretrizes atuais.",checkpoint:"O diagnóstico eletrocardiográfico não define sozinho risco tromboembólico nem tratamento."}]},
 {id:"arr-03",order:13,track:"arritmias",title:"Taquicardias de QRS estreito",subtitle:"Regularidade, atividade atrial e relação RP/PR",duration:"30 min",sourceCourseId:"385+545",status:"reviewed",visual:"svt",objectives:["Aplicar um algoritmo descritivo","Separar ritmos regulares e irregulares","Procurar atividade atrial","Comparar taquicardia por reentrada nodal e atrioventricular"],steps:[
  {title:"QRS estreito localiza a ativação ventricular",explanation:"Em geral, QRS estreito durante taquicardia indica que os ventrículos foram ativados pelo sistema His–Purkinje. Isso favorece origem supraventricular, mas não identifica sozinho qual arritmia atrial ou circuito está presente.",checkpoint:"Primeiro confirme a duração; depois analise regularidade e atividade atrial."},
  {title:"Se for irregular, reduza as hipóteses",explanation:"Taquicardia estreita irregular direciona a análise para fibrilação atrial, flutter com condução variável ou taquicardia atrial multifocal. Ondas P/F e o padrão da linha de base separam essas possibilidades.",checkpoint:"Irregularidade deve ser demonstrada por vários intervalos R–R, não por uma única pausa."},
  {title:"Se for regular, procure P e meça RP",explanation:"Ondas atriais visíveis antes ou depois do QRS, sua polaridade e a distância até o QRS ajudam a distinguir taquicardia atrial, reentrada nodal e reentrada por via acessória. Em algumas taquicardias, a P retrógrada fica escondida no QRS.",checkpoint:"P não visível não significa ausência de atividade atrial."},
  {title:"Reentrada nodal",explanation:"Na forma comum, átrios e ventrículos são ativados quase simultaneamente. A onda P retrógrada pode ficar dentro do QRS ou aparecer como pequena deflexão terminal nas derivações inferiores ou em V1.",checkpoint:"Uma pequena deflexão terminal só ganha significado se surgir durante a taquicardia e for coerente entre derivações."},
  {title:"Reentrada atrioventricular",explanation:"Uma via acessória participa do circuito. Na forma ortodrômica, o impulso desce pelo nó AV e retorna ao átrio pela via, produzindo QRS estreito e P retrógrada depois do QRS. O intervalo RP e a sequência atrial ajudam no diagnóstico diferencial.",checkpoint:"Pré-excitação pode não estar visível durante a taquicardia ortodrômica."}]},
 {id:"arr-04",order:14,track:"arritmias",title:"Taquicardias de QRS largo",subtitle:"Trate o traçado como risco até demonstrar o contrário",duration:"34 min",sourceCourseId:"430+546",status:"mapped",visual:"vt",objectives:["Construir o diagnóstico diferencial","Reconhecer dissociação AV, captura e fusão","Entender a lógica dos algoritmos morfológicos","Evitar falsa segurança"],steps:[
  {title:"O diferencial começa amplo",explanation:"Taquicardia de QRS largo pode representar taquicardia ventricular, taquicardia supraventricular com aberrância, bloqueio de ramo preexistente ou condução por via acessória. Em adultos, especialmente com cardiopatia estrutural, a origem ventricular deve ser considerada prioritariamente.",checkpoint:"Nunca rotule como supraventricular apenas porque a pessoa parece estável."},
  {title:"Procure evidência de independência atrial",explanation:"Dissociação AV, batimentos de captura e batimentos de fusão são pistas fortes de origem ventricular. Eles exigem observar séries longas e comparar morfologias, pois podem ser discretos.",checkpoint:"Uma frequência ventricular maior que a atrial favorece dissociação, mas a relação precisa ser demonstrada."},
  {title:"Morfologia testa compatibilidade",explanation:"Algoritmos como Brugada e o raciocínio pela derivação aVR avaliam se a sequência de ativação é compatível com condução pelo sistema normal ou com origem ventricular. Ausência de RS precordial, intervalo RS prolongado e morfologias incompatíveis com bloqueios típicos são exemplos de pistas.",checkpoint:"Não misture etapas de algoritmos diferentes nem modifique seus limites sem validação."},
  {title:"Contexto modifica probabilidade, não substitui o ECG",explanation:"Infarto prévio, cardiomiopatia, cicatriz e insuficiência cardíaca elevam a probabilidade de TV. Ainda assim, o laudo deve registrar os achados eletrocardiográficos que sustentam a conclusão.",checkpoint:"Antecedente clínico forte não autoriza inventar critérios ausentes."},
  {title:"Segurança",explanation:"Taquicardia de QRS largo pode ser emergência. O aplicativo ensina reconhecimento e não oferece tratamento. Instabilidade, síncope, dor torácica ou falta de ar exigem atendimento urgente.",checkpoint:"ALGORITMOS NUMÉRICOS AINDA NÃO LIBERADOS EM DESAFIOS ATÉ VALIDAÇÃO EXTERNA ATUAL."}]},
 {id:"arr-05",order:15,track:"arritmias",title:"Risco arrítmico e morte súbita",subtitle:"Por que nenhum marcador isolado é suficiente",duration:"24 min",sourceCourseId:"439+440+525",status:"mapped",visual:"pvt",objectives:["Entender substrato, gatilho e moduladores","Conhecer o papel e os limites de marcadores","Reconhecer alternância de T como fenômeno de repolarização"],steps:[
  {title:"Risco nasce de uma combinação",explanation:"Cicatriz ou canalopatia formam o substrato; extrassístoles e eventos agudos podem atuar como gatilhos; alterações autonômicas e metabólicas modulam a vulnerabilidade. O ECG mostra partes desse sistema, não uma previsão determinística.",checkpoint:"Um marcador de risco não equivale a diagnóstico de morte súbita futura."},
  {title:"Muitos métodos, respostas diferentes",explanation:"ECG de alta resolução, Holter, variabilidade da frequência, teste ergométrico, alternância de T, estudo eletrofisiológico e genética avaliam aspectos distintos. Desempenho e utilidade dependem da população e do contexto.",checkpoint:"Sensibilidade, especificidade e valor preditivo não podem ser transferidos automaticamente entre populações."},
  {title:"Alternância da onda T",explanation:"Alternância é variação batimento a batimento da amplitude ou forma da repolarização. Pode ser macroscópica ou em microvolts e relaciona-se à heterogeneidade temporal e espacial da recuperação ventricular.",checkpoint:"Artefato, ectopia e mudança de frequência podem simular alternância; o método de medição importa."},
  {title:"Conteúdo histórico exige atualização",explanation:"As aulas apresentam estudos e tecnologias de diferentes épocas. O beta preserva o conceito eletrofisiológico, mas não transforma resultados históricos em recomendação clínica atual.",checkpoint:"CRITÉRIOS DE ESTRATIFICAÇÃO E CONDUTA PERMANECEM FORA DOS DESAFIOS."}]},
 {id:"pace-01",order:17,track:"marcapasso",title:"ECG com marcapasso artificial",subtitle:"Espícula, captura, sensibilidade e modos de estimulação",duration:"38 min",sourceCourseId:"432+531+437",status:"mapped",visual:"paced",objectives:["Ler o código de estimulação","Reconhecer captura e sensibilidade","Separar disfunção de comportamento programado","Entender arritmias conduzidas, mediadas e induzidas"],steps:[
  {title:"Encontre a espícula e sua consequência",explanation:"Uma espícula atrial deve ser seguida de despolarização atrial; uma ventricular, de QRS estimulado. A ausência de espícula, a ausência de resposta depois dela e a emissão em momento inadequado representam problemas diferentes.",checkpoint:"Espícula sem resposta sugere falha de captura; atividade intrínseca ignorada sugere problema de sensibilidade."},
  {title:"O código descreve o comportamento",explanation:"As letras indicam câmara estimulada, câmara sentida, resposta ao sensoriamento, modulação de frequência e estimulação multissítio. A leitura do ECG deve verificar se o comportamento observado é compatível com o modo programado.",checkpoint:"Não memorize apenas DDD ou VVI; traduza cada posição relevante."},
  {title:"Captura, undersensing e oversensing",explanation:"Perda de captura ocorre quando o estímulo não despolariza a câmara. Undersensing é falha em perceber atividade intrínseca; oversensing é interpretação indevida de outro sinal como atividade cardíaca, inibindo ou modificando a estimulação.",checkpoint:"Descreva espícula, atividade intrínseca e resposta em ordem temporal."},
  {title:"Pseudodisfunção existe",explanation:"Histerese, períodos refratários, blanking, mudança de modo e mecanismos de resposta de frequência podem produzir intervalos inesperados sem defeito do dispositivo. Comparar o traçado ao modo e à programação evita diagnóstico falso.",checkpoint:"Um intervalo diferente não prova mau funcionamento."},
  {title:"Marcapasso e taquicardia",explanation:"O dispositivo pode conduzir uma arritmia atrial, participar de uma taquicardia mediada ou, raramente, contribuir para arritmia induzida. Relação entre eventos atriais, ventriculares e espículas separa os mecanismos.",checkpoint:"CONTEÚDO DE DISPOSITIVOS AINDA SEM DESAFIOS; avaliação real exige especialista e interrogatório do aparelho."}]},
 {id:"repo-01",order:18,track:"repolarizacao",title:"QT e repolarização ventricular",subtitle:"Meça com método e interprete no contexto",duration:"24 min",sourceCourseId:"441+443",status:"mapped",visual:"qtlong",objectives:["Localizar o fim da onda T","Entender por que o QT varia com a frequência","Reconhecer limites de QTc e dispersão"],steps:[
  {title:"QT reúne ativação e recuperação",explanation:"O intervalo QT começa no início do QRS e termina no fim da onda T. Ele representa o tempo total da despolarização e da repolarização ventriculares, por isso não deve ser confundido com a duração isolada da onda T.",checkpoint:"Marque o início do QRS e o retorno final da T à linha de base."},
  {title:"A frequência modifica a medida",explanation:"O QT tende a encurtar quando a frequência aumenta e a alongar quando diminui. Fórmulas de correção estimam um QT ajustado, mas introduzem erros em frequências extremas e não substituem a inspeção do traçado.",checkpoint:"Informe a fórmula usada e confira se a onda U não foi incluída como parte da T."},
  {title:"Morfologia também importa",explanation:"T entalhada, bifásica, alternante ou de término pouco definido exige comparação entre derivações. Escolha uma derivação com final de T nítido e confirme a coerência em batimentos consecutivos.",checkpoint:"Se o fim da T não é confiável, registre a limitação em vez de inventar precisão."},
  {title:"Dispersão do QT é conteúdo histórico",explanation:"A aula discute dispersão entre derivações e alternância da onda T como marcadores de heterogeneidade. Esses conceitos ajudam a compreender repolarização, mas não serão usados como decisão clínica nem como regra isolada de risco no beta.",checkpoint:"LIMITES NUMÉRICOS E ESTRATIFICAÇÃO AINDA NÃO LIBERADOS EM DESAFIOS."}]},
 {id:"arr-06",order:16,track:"arritmias",title:"Extrassístoles e fibrilação atrial",subtitle:"Prematuridade, origem e organização atrial",duration:"30 min",sourceCourseId:"536",status:"mapped",visual:"af",objectives:["Reconhecer um batimento prematuro","Distinguir origem atrial, juncional e ventricular","Identificar o padrão da fibrilação atrial"],steps:[
  {title:"Prematuro significa antes do esperado",explanation:"Compare o acoplamento do batimento ao ritmo de base. Depois procure atividade atrial precedente, largura e morfologia do QRS, pausa subsequente e eventual fusão.",checkpoint:"Não chame um QRS diferente de extrassístole sem demonstrar que ele ocorreu precocemente."},
  {title:"Atrial, juncional ou ventricular",explanation:"Extrassístole atrial costuma apresentar P prematura de morfologia diferente e QRS conduzido; a juncional pode ter P retrógrada antes, dentro ou depois do QRS; a ventricular geralmente é larga e não precedida por P relacionada. Aberrância pode confundir.",checkpoint:"Use prematuridade, P e QRS em conjunto."},
  {title:"A pausa conta parte da história",explanation:"Uma extrassístole pode reiniciar o nó sinusal, produzir pausa incompleta, ser interpolada ou gerar batimento de fusão. O intervalo longo depois do evento não deve ser interpretado isoladamente.",checkpoint:"Compare a soma dos intervalos com o ciclo básico."},
  {title:"Fibrilação atrial",explanation:"Na fibrilação atrial não existem ondas P discretas e repetíveis; a atividade atrial é desorganizada e a resposta ventricular costuma ser irregularmente irregular, salvo interferências como bloqueio AV ou estimulação.",checkpoint:"Artefato pode simular linha de base fibrilatória; confirme em várias derivações."},
  {title:"Classificações antigas não viram regras",explanation:"Algumas classificações históricas de extrassístoles aparecem na aula. O beta ensina descrição e reconhecimento, sem transformar gradações antigas em prognóstico ou conduta atual.",checkpoint:"CONTEÚDO AINDA SEM DESAFIOS ATÉ VALIDAÇÃO EXTERNA."}]},
 {id:"repo-02",order:19,track:"repolarizacao",title:"Canalopatias e genética: reconhecer sem simplificar",subtitle:"QT longo, QT curto, Brugada e contexto familiar",duration:"34 min",sourceCourseId:"449+537+453+454",status:"pending",visual:"brugada",objectives:["Entender o conceito de doença elétrica primária","Reconhecer famílias de padrões","Saber os limites do ECG e do teste genético"],steps:[
  {title:"A estrutura pode parecer normal",explanation:"Canalopatias alteram correntes iônicas e podem modificar repolarização ou condução sem cardiopatia estrutural evidente. Fenótipo, sintomas, história familiar, medicamentos e eletrólitos precisam ser integrados.",checkpoint:"Um padrão eletrocardiográfico não equivale automaticamente a uma síndrome clínica."},
  {title:"QT longo e QT curto",explanation:"A duração e a forma da repolarização podem sugerir síndromes de QT longo ou curto, mas a medida depende de técnica, frequência, fórmula de correção e exclusão de causas adquiridas.",checkpoint:"Revise fármacos, eletrólitos e qualidade do traçado antes de atribuir causa hereditária."},
  {title:"Padrão de Brugada",explanation:"Alterações características nas precordiais direitas podem levantar a hipótese de padrão de Brugada. Posicionamento dos eletrodos, febre, medicamentos e diagnósticos diferenciais modificam a aparência.",checkpoint:"Não confunda padrão no ECG com diagnóstico completo da síndrome."},
  {title:"Genética não é um teste de sim ou não",explanation:"Uma variante patogênica pode apoiar diagnóstico e rastreamento familiar, mas resultado negativo não exclui doença e variantes de significado incerto não devem ser tratadas como confirmação.",checkpoint:"Interpretação genética requer equipe especializada e correlação fenotípica."},
  {title:"Segurança",explanation:"As aulas incluem critérios e recomendações de diferentes épocas. Até validação em consenso atual, esta aula permanece conceitual e sem desafios diagnósticos.",checkpoint:"CONTEÚDO PENDENTE DE VALIDAÇÃO ATUAL."}]},
 {id:"met-01",order:20,track:"metodos",title:"Holter, monitor de eventos e looper",subtitle:"Escolha o tempo de observação para o fenômeno",duration:"22 min",sourceCourseId:"473",status:"mapped",visual:"normal",objectives:["Diferenciar ECG instantâneo de monitorização prolongada","Relacionar frequência do sintoma ao método","Reconhecer artefatos e limites"],steps:[
  {title:"O ECG é uma amostra curta",explanation:"Eventos intermitentes podem não aparecer no traçado de repouso. Holter registra continuamente por período limitado; monitores de eventos e loopers ampliam a janela e podem depender de acionamento ou detecção automática.",checkpoint:"Quanto mais raro o evento, maior tende a ser a janela necessária."},
  {title:"Sintoma e ritmo precisam de relógio comum",explanation:"Diário, marcador de evento e horário preciso permitem comparar palpitação, síncope ou outro sintoma ao ritmo registrado. Um achado sem correlação temporal responde pergunta diferente.",checkpoint:"Ausência de arritmia durante um sintoma registrado é informação útil."},
  {title:"Artefato também dura horas",explanation:"Movimento, contato de eletrodo e ruído podem simular pausas, taquicardia ou fibrilação. Revise canais, início e fim do evento e coerência fisiológica.",checkpoint:"Detecção automática é triagem; traçados relevantes exigem revisão humana."}]},
 {id:"met-02",order:21,track:"metodos",title:"ECG durante o esforço",subtitle:"O traçado muda com carga, frequência e recuperação",duration:"34 min",sourceCourseId:"459+460+476+552+464",status:"pending",visual:"fast",objectives:["Entender fases do teste","Reconhecer limitações técnicas","Separar resposta elétrica, clínica e hemodinâmica"],steps:[
  {title:"Existe repouso, esforço e recuperação",explanation:"O teste aplica carga progressiva e registra sintomas, frequência, pressão e ECG em momentos definidos. Comparar cada estágio ao basal é mais informativo que uma imagem isolada.",checkpoint:"Sempre identifique o estágio e a qualidade do registro antes de interpretar ST."},
  {title:"Movimento gera ruído",explanation:"Oscilação da linha de base, tremor muscular e perda de contato aumentam durante exercício. A média computadorizada pode ajudar, mas também pode distorcer complexos e não substitui o traçado bruto.",checkpoint:"Uma alteração reproduzível em derivações coerentes é mais confiável que um ponto ruidoso."},
  {title:"ST não é a única resposta",explanation:"A leitura inclui frequência e recuperação, arritmias, pressão, capacidade funcional, sintomas e comportamento do QRS e da repolarização. Cada variável tem limites e contexto próprios.",checkpoint:"Um teste não pode ser classificado corretamente por uma única medida sem conhecer protocolo e contexto."},
  {title:"Protocolos antigos exigem revisão",explanation:"As aulas mostram protocolos, limiares e recomendações de épocas diferentes. O beta preserva a lógica de comparação seriada, mas não libera indicação, contraindicação ou interpretação clínica numérica.",checkpoint:"CONTEÚDO PENDENTE DE DIRETRIZ ATUAL E FORA DOS DESAFIOS."}]},
 {id:"met-03",order:22,track:"metodos",title:"O que o estudo eletrofisiológico acrescenta",subtitle:"Do ECG de superfície aos sinais intracavitários",duration:"24 min",sourceCourseId:"469",status:"mapped",visual:"fast",objectives:["Entender registros intracavitários","Relacionar intervalos à anatomia da condução","Compreender indução e mapeamento sem ensinar procedimento"],steps:[
  {title:"Cateteres observam pontos internos",explanation:"Eletrogramas atriais, do feixe de His e ventriculares permitem separar etapas que o ECG de superfície reúne. Intervalos intracavitários localizam atrasos e ajudam a esclarecer mecanismos.",checkpoint:"ECG de superfície e eletrograma intracavitário são sinais diferentes e complementares."},
  {title:"Estimulação testa o sistema",explanation:"Estímulos programados avaliam condução, refratariedade e possibilidade de iniciar ou interromper circuitos. A resposta temporal ajuda no diagnóstico diferencial de taquicardias.",checkpoint:"Induzir uma arritmia em laboratório não é o mesmo que reconhecê-la apenas pelo ECG de repouso."},
  {title:"Mapeamento procura origem ou circuito",explanation:"Tempos de ativação e resposta ao estímulo ajudam a localizar foco, via acessória ou parte crítica de uma reentrada. Ablação e risco procedimental não fazem parte do escopo do jogo.",checkpoint:"A plataforma ensina o conceito; não orienta indicação nem execução de procedimento."}]},
 {id:"met-04",order:23,track:"metodos",title:"Computadores leem medidas, pessoas validam sentido",subtitle:"Algoritmos, transmissão e segurança da informação",duration:"18 min",sourceCourseId:"478+480",status:"reviewed",visual:"normal",objectives:["Entender benefícios da análise automática","Reconhecer falhas sistemáticas","Valorizar revisão humana e privacidade"],steps:[
  {title:"Automação mede e organiza",explanation:"Software pode detectar batimentos, medir intervalos, comparar registros, armazenar e transmitir exames. Isso reduz trabalho repetitivo e amplia acesso, mas depende de sinal adequado e regras explícitas.",checkpoint:"Uma medida automática precisa ser conferida quando não combina com o traçado."},
  {title:"O algoritmo pode errar com confiança",explanation:"Ruído, variantes normais, pediatria, marcapasso e padrões complexos desafiam interpretações automáticas. A saída do computador é uma hipótese estruturada, não autoridade clínica.",checkpoint:"Confira calibração, marcações e diagnóstico sugerido antes de aceitar o laudo."},
  {title:"Transmitir não elimina responsabilidade",explanation:"Tele-ECG permite avaliação remota síncrona ou assíncrona. Qualidade do sinal, identificação correta, privacidade, tempo de resposta e responsabilidade profissional continuam essenciais.",checkpoint:"A plataforma não recebe ECG de paciente nem envia dados clínicos."}]},
 {id:"met-05",order:24,track:"metodos",title:"Laboratório cumulativo de traçados",subtitle:"Descreva primeiro, conclua depois",duration:"26 min",sourceCourseId:"482",status:"mapped",visual:"normal",objectives:["Integrar frequência, ritmo, condução e repolarização","Comparar diagnósticos próximos","Justificar cada conclusão"],steps:[
  {title:"Use sempre a mesma ordem",explanation:"Validade, frequência, regularidade, P, relação AV, PR, QRS, eixo, progressão de R, ST, T e QT. A ordem reduz omissões quando o caso contém mais de uma alteração.",checkpoint:"Não permita que o primeiro achado encerre a leitura."},
  {title:"Liste achados independentes",explanation:"Um traçado pode combinar bloqueio de ramo, bloqueio fascicular, sobrecarga, ectopia ou alteração de repolarização. Cada item precisa de evidência própria.",checkpoint:"Se dois diagnósticos usam o mesmo achado, procure o critério que realmente os separa."},
  {title:"A imagem deve responder à pergunta",explanation:"Nos desafios do beta, cada traçado sintético destaca o elemento solicitado e informa a derivação ou foco visual. Não são usadas imagens nem casos do curso.",checkpoint:"Se o elemento perguntado não estiver visível, a questão deve ser retirada, não adivinhada."}]},
 {id:"emer-01",order:25,track:"emergencias",title:"ST, T e síndrome coronariana",subtitle:"Localização, contiguidade e alterações recíprocas",duration:"22 min",sourceCourseId:"340",status:"pending",visual:"ischemia",objectives:["Analisar ST e T em contexto","Usar derivações contíguas","Reconhecer diferenciais"],steps:[
  {title:"Repolarização depende do QRS",explanation:"ST e T são avaliados em relação ao final do QRS, à linha de base e à distribuição entre derivações. Alterações secundárias acompanham alguns distúrbios de condução.",checkpoint:"Não interprete ST isoladamente sem olhar QRS e vizinhas."},
  {title:"T, ST e Q contam fases diferentes",explanation:"A aula organiza os achados em alterações da onda T relacionadas à isquemia, deslocamentos do segmento ST relacionados à corrente de lesão e ondas Q patológicas associadas a área eletricamente inativa. Na prática, esses padrões variam e podem coexistir.",checkpoint:"Não determine tempo, reversibilidade ou anatomia apenas pelo nome de uma onda."},
  {title:"Território é padrão distribuído",explanation:"Alterações coerentes em derivações contíguas e imagens recíprocas fortalecem uma hipótese. A localização considera planos frontal e horizontal e pode exigir derivações direitas ou posteriores.",checkpoint:"Uma única derivação alterada não define território."},
  {title:"Bloqueios não encerram a investigação",explanation:"BRD não impede avaliar alterações de ST. No BRE, a repolarização secundária dificulta a leitura e critérios específicos podem ser necessários.",checkpoint:"Não aplique regras de QRS estreito sem considerar o distúrbio de condução."},
  {title:"Diagnósticos diferenciais são obrigatórios",explanation:"Repolarização precoce, pericardite, sobrecarga ventricular, distúrbios metabólicos, hipercalemia, hipercalcemia e padrões de condução podem simular alterações coronarianas.",checkpoint:"CONTEÚDO DE EMERGÊNCIA AINDA SEM DESAFIOS; não usar para decisão clínica."},
  {title:"Dor torácica é situação clínica",explanation:"Sintomas compatíveis com síndrome coronariana exigem avaliação urgente. Um aplicativo educacional não exclui emergência por ECG aparentemente normal nem define tratamento.",checkpoint:"Acione o serviço de emergência diante de sintomas reais; não espere o jogo interpretar."}]},
 {id:"emer-02",order:26,track:"emergencias",title:"Ritmos de parada e o DEA",subtitle:"Reconheça o traçado, mas deixe o aparelho decidir o choque",duration:"14 min",sourceCourseId:"aha-2025-cardiac-arrest",status:"reviewed",visual:"vf",objectives:["Reconhecer FV, TV sem pulso, assistolia e AESP","Separar ritmos chocáveis de não chocáveis","Aplicar a resposta segura com DEA"],steps:[
  {title:"Primeiro reconheça a parada",explanation:"Pessoa inconsciente, sem respiração normal ou apenas com gasping exige acionamento imediato do serviço de emergência, início de RCP e obtenção de um DEA. Para leigos, o foco é reconhecer a situação e agir; não perder tempo tentando interpretar o monitor.",checkpoint:"Chame ajuda, inicie RCP e use o DEA assim que estiver disponível."},
  {title:"FV e TV sem pulso são chocáveis",explanation:"Fibrilação ventricular mostra atividade ventricular caótica, sem complexos organizados. Taquicardia ventricular sem pulso costuma apresentar atividade ventricular rápida e larga. No algoritmo de parada, ambas pertencem ao ramo chocável.",checkpoint:"O termo “sem pulso” depende da avaliação da pessoa, não apenas do desenho do ECG."},
  {title:"Assistolia e AESP não são chocáveis",explanation:"Assistolia é ausência de atividade elétrica discernível. AESP é atividade elétrica organizada sem pulso efetivo. No algoritmo, recebem RCP e busca de causas reversíveis; o choque não é indicado.",checkpoint:"Uma linha aparentemente plana exige conferir cabos e mais de uma derivação em ambiente profissional."},
  {title:"O DEA toma a decisão",explanation:"Ligue o aparelho, exponha e seque o tórax, coloque as pás como indicado e siga as instruções. Afaste todos durante a análise e, se o DEA recomendar choque, garanta que ninguém toca a pessoa antes de apertar o botão. Retome RCP quando orientado.",checkpoint:"Nunca toque na pessoa durante análise ou choque. Este resumo não substitui curso certificado de RCP/DEA."}]}
];
